name: dospace
description: Client library to interact with the DigitalOcean Spaces API. Same
  API as Amazon AWS S3.
version: 0.12.13
homepage: https://github.com/nbspou/dospace
author: NO-BREAK SPACE OÃœ <support@no-break.space>

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  crypto: ^3.0.7
  http: ^1.0.0
  meta: "1.16.0"
  mime: ^2.0.0
  xml: ^6.5.0

dev_dependencies:
  ini: ^2.1.0
  test: ^1.16.8
